#!/bin/bash

# Screenshot Helper Script
# This script displays URLs and commands to help you take screenshots systematically

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Get EC2 IP if available
if [ -f ".env.aws" ]; then
    EC2_IP=$(grep EC2_PUBLIC_IP .env.aws | cut -d '=' -f2)
else
    EC2_IP="<YOUR-EC2-IP>"
fi

clear
echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║       AWS Deployment - Screenshot Capture Guide               ║${NC}"
echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo ""

# Section 1: AWS Console Screenshots
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 1: AWS Console Screenshots${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 1.1: EC2 Dashboard${NC}"
echo "URL: https://console.aws.amazon.com/ec2/v2/home"
echo "Capture: Overview showing running instances, t2.micro type"
echo ""
echo -e "${YELLOW}Screenshot 1.2: Instance Details${NC}"
echo "Steps: Select your instance → Details tab"
echo "Capture: Instance ID, type (t2.micro), AMI, State (running)"
echo ""
echo -e "${YELLOW}Screenshot 1.3: Security Groups${NC}"
echo "Steps: Select instance → Security tab → Security groups"
echo "Capture: Inbound rules showing all ports (22, 80, 5001-5005, 8080)"
echo ""
echo -e "${YELLOW}Screenshot 1.4: CloudWatch Metrics${NC}"
echo "Steps: Select instance → Monitoring tab"
echo "Capture: CPU utilization, Network in/out graphs"
echo ""
echo -e "${YELLOW}Screenshot 1.5: Billing Dashboard${NC}"
echo "URL: https://console.aws.amazon.com/billing/home"
echo "Capture: Current month charges showing \$0.00"
echo ""
read -p "Press Enter when Section 1 screenshots are complete..."

# Section 2: Docker & Containers
clear
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 2: Docker Containers & Services${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 2.1: Running Containers${NC}"
echo "Command: ${CYAN}docker ps${NC}"
echo "Capture: All containers showing (backend, frontend, kafka, etc.)"
echo ""
docker ps
echo ""
echo -e "${YELLOW}Screenshot 2.2: Docker Stats${NC}"
echo "Command: ${CYAN}docker stats --no-stream${NC}"
echo "Capture: Resource usage (CPU%, MEM usage) for all containers"
echo ""
docker stats --no-stream
echo ""
echo -e "${YELLOW}Screenshot 2.3: Container Logs${NC}"
echo "Command: ${CYAN}docker logs backend --tail 30${NC}"
echo "Capture: Backend logs showing successful startup"
echo ""
docker logs backend --tail 30 2>&1 | head -20
echo "..."
echo ""
read -p "Press Enter when Section 2 screenshots are complete..."

# Section 3: Application URLs
clear
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 3: Application Access${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 3.1: Frontend Application${NC}"
echo "URL: ${CYAN}http://${EC2_IP}:5173${NC}"
echo "Capture: Homepage, search page, property listings"
echo ""
echo -e "${YELLOW}Screenshot 3.2: Backend API Health${NC}"
echo "URL: ${CYAN}http://${EC2_IP}:5001/health${NC}"
echo "Command: ${CYAN}curl http://${EC2_IP}:5001/health${NC}"
echo "Capture: JSON response showing service healthy"
echo ""
echo -e "${YELLOW}Screenshot 3.3: Property Service${NC}"
echo "URL: ${CYAN}http://${EC2_IP}:5003/api/properties${NC}"
echo "Capture: Property listings JSON response"
echo ""
echo -e "${YELLOW}Screenshot 3.4: Booking Service${NC}"
echo "URL: ${CYAN}http://${EC2_IP}:5004/health${NC}"
echo "Capture: Service health response"
echo ""
echo -e "${YELLOW}Screenshot 3.5: Kafka UI${NC}"
echo "URL: ${CYAN}http://${EC2_IP}:8080${NC}"
echo "Capture: Topics list, brokers, consumer groups"
echo ""
read -p "Press Enter to open URLs (requires xdg-open or open command)..."

# Section 4: Kafka Screenshots
clear
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 4: Kafka Message Queue${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 4.1: Kafka Topics${NC}"
echo "Command: ${CYAN}docker exec kafka kafka-topics --list --bootstrap-server localhost:9092${NC}"
echo "Capture: List of topics (booking-requests, booking-updates)"
echo ""
docker exec kafka kafka-topics --list --bootstrap-server localhost:9092 2>/dev/null || echo "Kafka not ready"
echo ""
echo -e "${YELLOW}Screenshot 4.2: Kafka UI - Topics${NC}"
echo "URL: ${CYAN}http://${EC2_IP}:8080${NC}"
echo "Capture: Topics tab showing partitions, messages"
echo ""
echo -e "${YELLOW}Screenshot 4.3: Kafka UI - Messages${NC}"
echo "Capture: Click on booking-requests → Messages tab"
echo "Show: Sample messages in the queue"
echo ""
echo -e "${YELLOW}Screenshot 4.4: Producer Logs${NC}"
echo "Command: ${CYAN}docker logs booking-service --tail 20${NC}"
echo "Capture: Logs showing Kafka message production"
echo ""
read -p "Press Enter when Section 4 screenshots are complete..."

# Section 5: Redux & Frontend
clear
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 5: Redux State Management${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 5.1: Redux DevTools - State Tree${NC}"
echo "Steps:"
echo "1. Open frontend: ${CYAN}http://${EC2_IP}:5173${NC}"
echo "2. Open Chrome DevTools (F12)"
echo "3. Go to Redux tab"
echo "4. Capture: State tree showing auth, properties, bookings"
echo ""
echo -e "${YELLOW}Screenshot 5.2: Redux DevTools - Actions${NC}"
echo "Steps:"
echo "1. Perform login action"
echo "2. Go to Action tab in Redux DevTools"
echo "3. Capture: Action history showing LOGIN_SUCCESS, etc."
echo ""
echo -e "${YELLOW}Screenshot 5.3: Redux DevTools - Diff${NC}"
echo "Steps:"
echo "1. Perform a property search"
echo "2. Click on action → Diff tab"
echo "3. Capture: State changes (before/after)"
echo ""
echo -e "${YELLOW}Screenshot 5.4: Network Tab${NC}"
echo "Steps:"
echo "1. Open Network tab in DevTools"
echo "2. Perform booking action"
echo "3. Capture: API calls to backend services"
echo ""
read -p "Press Enter when Section 5 screenshots are complete..."

# Section 6: Architecture & System
clear
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 6: System Architecture${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 6.1: System Resources${NC}"
echo "Command: ${CYAN}free -m${NC}"
echo "Capture: Memory usage"
echo ""
free -m
echo ""
echo -e "${YELLOW}Screenshot 6.2: Disk Usage${NC}"
echo "Command: ${CYAN}df -h${NC}"
echo "Capture: Disk space usage"
echo ""
df -h
echo ""
echo -e "${YELLOW}Screenshot 6.3: Network Connections${NC}"
echo "Command: ${CYAN}netstat -tulpn | grep LISTEN${NC}"
echo "Capture: Services listening on ports"
echo ""
sudo netstat -tulpn 2>/dev/null | grep LISTEN || netstat -an | grep LISTEN
echo ""
echo -e "${YELLOW}Screenshot 6.4: Docker Compose Config${NC}"
echo "Command: ${CYAN}cat docker-compose.aws.yml${NC}"
echo "Capture: Configuration file (can do in VS Code)"
echo ""
read -p "Press Enter when Section 6 screenshots are complete..."

# Section 7: Testing & Performance
clear
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SECTION 7: Testing & Performance${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Screenshot 7.1: API Response Time${NC}"
echo "Command: ${CYAN}time curl http://${EC2_IP}:5001/health${NC}"
echo "Capture: Response time measurement"
echo ""
echo -e "${YELLOW}Screenshot 7.2: Load Test (if JMeter available)${NC}"
echo "Steps:"
echo "1. Run JMeter test plan"
echo "2. Capture: Results tree, response times graph"
echo ""
echo -e "${YELLOW}Screenshot 7.3: Service Health Checks${NC}"
echo "Commands:"
echo "${CYAN}curl http://${EC2_IP}:5001/health${NC}"
echo "${CYAN}curl http://${EC2_IP}:5003/health${NC}"
echo "${CYAN}curl http://${EC2_IP}:5004/health${NC}"
echo "Capture: All health check responses"
echo ""
read -p "Press Enter when Section 7 screenshots are complete..."

# Summary
clear
echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║              Screenshot Capture Complete! ✅                   ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Checklist Summary:${NC}"
echo ""
echo "AWS Console:"
echo "  ✓ EC2 Dashboard"
echo "  ✓ Instance Details"
echo "  ✓ Security Groups"
echo "  ✓ CloudWatch Metrics"
echo "  ✓ Billing (showing \$0)"
echo ""
echo "Docker & Services:"
echo "  ✓ Running containers (docker ps)"
echo "  ✓ Resource usage (docker stats)"
echo "  ✓ Service logs"
echo ""
echo "Application:"
echo "  ✓ Frontend UI"
echo "  ✓ Backend API"
echo "  ✓ Property Service"
echo "  ✓ Booking Service"
echo "  ✓ Kafka UI"
echo ""
echo "Kafka:"
echo "  ✓ Topics list"
echo "  ✓ Message queue UI"
echo "  ✓ Producer/Consumer logs"
echo ""
echo "Redux:"
echo "  ✓ State tree"
echo "  ✓ Action history"
echo "  ✓ State diffs"
echo "  ✓ Network calls"
echo ""
echo "System:"
echo "  ✓ Memory usage"
echo "  ✓ Disk usage"
echo "  ✓ Network ports"
echo "  ✓ Configuration files"
echo ""
echo -e "${YELLOW}📝 Next Steps:${NC}"
echo "1. Organize screenshots into folders"
echo "2. Add captions/annotations"
echo "3. Include in final report"
echo "4. Document architecture decisions"
echo ""
echo -e "${CYAN}Report Sections to Complete:${NC}"
echo "• Architecture Overview"
echo "• AWS Deployment Strategy"
echo "• Kafka Implementation"
echo "• Redux State Management"
echo "• Cost Analysis & Optimization"
echo "• Performance Testing Results"
echo "• Lessons Learned"
echo ""
echo -e "${GREEN}Good luck with your report! 🎓${NC}"
